#!/bin/bash

# What modules, in what order
MODULES="internet wifi cputemp battery time date"

# Modules that require an active internet connection
ONLINE_MODULES="internet"

# Delay between showing the status bar
DELAY="5"

# Where the custom modules are stored
CUSTOM_DIR="/home/$USER/.config/dwmbar/modules/custom/"

# Separator between modules
SEPARATOR=" | "

# Padding at the end and beginning of the status bar
RIGHT_PADDING=" "
LEFT_PADDING=" "
